version: '3.8'

services:
  nats:
    image: nats:latest
    command: ['-c', '/etc/nats/nats-server.conf']
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf:ro
      - nats_data:/data
    restart: unless-stopped

  publisher:
    build: ./publisher
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222

  subscriber:
    build: ./subscriber
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - PROCESS_MS=10000

volumes:
  nats_data:
